---

XGUI:
  xsession_path: /usr/bin/xinit
  xterm_path: /usr/bin/xterm
  vnc_dependencies:
    - xterm
    - git
    - numpy
    - openssl
  packages_to_remove:
    - vnc-server
  packages:
    - xorg-x11-xauth


REQUIRED:
  files_to_add:
    - { FROM: "config.insecure", TO: "/home/{{ ATMOUSERNAME }}/.vnc/config.insecure", STATE: present, MODE: "700", OWNER: "{{ ATMOUSERNAME }}" }
    - { FROM: "config.custom", TO: "/home/{{ ATMOUSERNAME }}/.vnc/config.custom", STATE: present, MODE: "700", OWNER: "root" }
  files_to_remove:
    - { PATH: /tmp/.X1-lock, STATE: absent }
    - { PATH: /tmp/.X11-unix, STATE: absent }
    - { PATH: /tmp/novnc.tar, STATE: absent }
  dirs_to_make:
    - { PATH: /tmp/.X11-unix, STATE: directory, MODE: "a+rwxt", OWNER: "root" }
    - { PATH: "/home/{{ ATMOUSERNAME }}", STATE: directory, MODE: "0750", OWNER: "{{ ATMOUSERNAME }}" }
    - { PATH: "/home/{{ ATMOUSERNAME }}/.vnc", STATE: directory, MODE: "0750", OWNER: "{{ ATMOUSERNAME }}" }

VNC_COMMANDS:
  - "/usr/bin/pkill gnome-screensaver"
  - "/usr/bin/pkill websockify"
  - "for i in $(/usr/bin/pgrep -f '/opt/kanaka-noVNC-8b0a0f6/utils/');do /bin/echo 'killing process:' $i; /bin/kill -HUP $i;done"
  - /usr/bin/vnclicense -add {{ VNCLICENSE }}
  - /bin/su {{ ATMOUSERNAME }} -c /usr/bin/vncserver :1
