---

XGUI:
  xsession_path: /usr/bin/xinit
  xterm_path: /usr/bin/xterm
  vnc_dependencies:
    - xterm
    - git
    - numpy
    - openssl
  packages_to_remove:
    # - realvnc-vnc-server
    - vnc-server
  packages:
    - xorg-x11-xauth
    # - vnc-server


REQUIRED:
  files_to_add:
    - { FROM: "config.insecure", TO: "/home/{{ ATMOUSERNAME }}/.vnc/config.insecure", STATE: present, MODE: "700", OWNER: "{{ ATMOUSERNAME }}" }
    - { FROM: "config.custom", TO: "/home/{{ ATMOUSERNAME }}/.vnc/config.custom", STATE: present, MODE: "700", OWNER: "root" }
    #, GROUP: "{{ ATMOUSERNAME }}" }
  files_to_remove:
    - { PATH: /tmp/.X1-lock, STATE: absent }
    - { PATH: /tmp/.X11-unix, STATE: absent }
    # - { PATH: /tmp/VNC-Server-5.2.3-Linux-x64.rpm, STATE: absent }
    # - { PATH: /tmp/VNC-Server-5.2.3-Linux-x64.deb, STATE: absent }
    # - { PATH: /opt/VNC-Server-5.2.3-Linux-x64.rpm, STATE: absent }
    # - { PATH: /opt/VNC-Server-5.2.3-Linux-x64.deb, STATE: absent }
    - { PATH: /tmp/novnc.tar, STATE: absent }
    # - { PATH: /etc/pam.d/vncserver.custom, STATE: absent }
    # - { PATH: /etc/vnc/config.d/common.custom, STATE: absent }
    # - { PATH: /etc/vnc/config.custom, STATE: absent }
  dirs_to_make:
    - { PATH: /tmp/.X11-unix, STATE: directory, MODE: "a+rwxt", OWNER: "root" }
    #, GROUP: "root" }
    - { PATH: "/home/{{ ATMOUSERNAME }}", STATE: directory, MODE: "0750", OWNER: "{{ ATMOUSERNAME }}" }
    #, GROUP: "{{ ATMOUSERNAME }}" }
    - { PATH: "/home/{{ ATMOUSERNAME }}/.vnc", STATE: directory, MODE: "0750", OWNER: "{{ ATMOUSERNAME }}" }
    #, GROUP: "{{ ATMOUSERNAME }}" }

VNC_COMMANDS:
  - "/usr/bin/pkill gnome-screensaver"
  #- /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/printf '%s\n%s\n' 'display' 'display' | vncpasswd {{ NOVNC.passwd_file }}"
  - "/usr/bin/pkill websockify"
  - "for i in $(/usr/bin/pgrep -f '/opt/kanaka-noVNC-8b0a0f6/utils/');do /bin/echo 'killing process:' $i; /bin/kill -HUP $i;done"
  - /usr/bin/vnclicense -add {{ VNCLICENSE }}
  - /bin/su {{ ATMOUSERNAME }} -c /usr/bin/vncserver :1
  #- "/bin/su {{ ATMOUSERNAME }} -c '/usr/bin/vncserver -localhost :{{ NOVNC.vnc_session }} -vncconfigfile {{ NOVNC.config_file }}'"
  # To disable NoVNC web when entering prod, remove "--web /usr/share/novnc/" from the command below
  #- "/opt/kanaka-noVNC-8b0a0f6/utils/launch.sh --listen {{ NOVNC.socket_port }} --vnc localhost:{{ NOVNC.vnc_port }} &"
