---

XGUI:
  xsession_path: /usr/bin/X
  xterm_path: /usr/bin/xinit
  vnc_dependencies:
    - libfam0
    - libxext-dev
    - libx11-dev
    - libc6-dev
    - libthunar-vfs-1-2
    - libc6
    - git
  packages_to_remove:
    - novnc
  packages:
    - git

VNC_COMMANDS:
  - "/usr/bin/pkill gnome-screensaver"
  - /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/printf '%s\n%s\n' 'display' 'display' | vncpasswd {{ NOVNC.passwd_file }}"
  - "/usr/bin/pkill websockify"
  - /usr/bin/vnclicense -add {{ VNCLICENSE }}
  - /bin/su {{ ATMOUSERNAME }} -c /usr/bin/vncserver :1
  - "for i in $(/usr/bin/pgrep -f '/opt/kanaka-noVNC-8b0a0f6/utils/');do /bin/echo 'killing process:' $i; /bin/kill -HUP $i;done"
  - "/bin/su {{ ATMOUSERNAME }} -c '/usr/bin/vncserver -localhost :{{ NOVNC.vnc_session }} -SecurityTypes=VNCAuth,TLSVnc'"
  # To disable NoVNC web when entering prod, remove "--web /usr/share/novnc/" from the command below
  - "/opt/kanaka-noVNC-8b0a0f6/utils/launch.sh --listen {{ NOVNC.socket_port }} --vnc localhost:{{ NOVNC.vnc_port }} &"
