---

XGUI:
  xsession_path: /usr/bin/X
  xterm_path: /usr/bin/xinit
  vnc_dependencies:
    - libfam0
    - libxext-dev
    - libx11-dev
    - libc6-dev
    - libc6
    - git
  packages_to_remove:
    - vnc4server
  packages:
    - novnc
