---
# Requires ATMOUSERNAME and VNCLICENSE
- name: Playbook lists roles that should be executed after ATMOUSERNAME has been created
  hosts: atmosphere
  roles:
    - { role: atmo-fail2ban, when: true }
    - { role: irods-icommands, when: SETUP_IRODS_ICOMMANDS is defined and SETUP_IRODS_ICOMMANDS == true }
    - { role: atmo-realvncserver, when: SETUP_REALVNC_SERVER is defined and SETUP_REALVNC_SERVER == true }
    - { role: atmo-guacamole, when: SETUP_GUACAMOLE is defined and SETUP_GUACAMOLE == true }
    - { role: atmo-cleanup, when: true }
