---
# Requires ATMOUSERNAME and VNCLICENSE
- name: Playbook lists roles that should be executed after ATMOUSERNAME has been created
  hosts: atmosphere
  roles:
    - atmo-fail2ban
    - { role: irods-icommands, when: SETUP_IRODS_ICOMMANDS is defined and SETUP_IRODS_ICOMMANDS == true }
    - { role: atmo-kanki-irodsclient, when: SETUP_IRODS_ICOMMANDS is defined and SETUP_IRODS_ICOMMANDS == true }
    - { role: install-browser, when: SETUP_GUI_BROWSER is defined and SETUP_GUI_BROWSER == true }
    - { role: atmo-realvncserver, when: SETUP_REALVNC_SERVER is defined and SETUP_REALVNC_SERVER == true }
    - atmo-cleanup
