- name: bootscript_1 - make directories for post scripts and logs
  file: path={{ item }} state=directory
  with_items: '{{ POST_MAKE_DIR }}'

- name: bootscript_2 - touch log files
  file: path={{ item }} state=touch
  with_items: '{{ POST_SCRIPT_LOGS }}'
  # The following two lines work around https://github.com/ansible/ansible-modules-core/issues/170
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: bootscript_3 - run user's scripts in script directory
  shell: >
    for SCRIPT in {{ POST_SCRIPT_DIR_RUN }};
    do
        if [ -f $SCRIPT -a -x $SCRIPT ]
        then
            ATMO_USER={{ ATMOUSERNAME }} $SCRIPT 2>> {{ POST_SCRIPT_LOG_STDERR }} >> {{ POST_SCRIPT_LOG_STDOUT }}
        fi
    done

- name: bootscript_4.1 - copy scripts to location
  copy:
    content: "{{ item.text }}"
    dest: "{{POST_SCRIPT_DIR}}/{{item.name}}"
    mode: "u+rwx"
  with_items: '{{ SCRIPTS }}'

- name: bootscript_4.2 - run scripts passed in to the playbook
  shell: >
    ATMO_USER={{ ATMOUSERNAME }} "{{POST_SCRIPT_DIR}}/{{ item.name }}" 2>> {{ POST_SCRIPT_LOG_STDERR }} >> {{ POST_SCRIPT_LOG_STDOUT }}
  with_items: '{{ SCRIPTS }}'

- name: bootscript_4.3 - remove scripts
  file:
    path: "{{POST_SCRIPT_DIR}}/{{ item.name }}"
    state: absent
  with_items: '{{ SCRIPTS }}'
