---

dependencies:
  - epel-release
  - openssl-devel
  - libcurl-devel
  - qt5-qtsvg-devel
  - qt5-qtbase-devel
  # instead of `yum groupinstall "Development Tools"`:
  - bison
  - byacc
  - cscope
  - ctags
  - cvs
  - diffstat
  - doxygen
  - flex
  - gcc
  - gcc-c++
  - gcc-gfortran
  - gettext
  - git
  - indent
  - intltool
  - libtool
  - patch
  - patchutils
  - rcs
  - redhat-rpm-config
  - rpm-build
  - subversion
  - swig
  - systemtap

irods_files:
  - ftp://ftp.renci.org/pub/irods/releases/4.1.9/centos6/irods-runtime-4.1.9-centos6-x86_64.rpm
  - ftp://ftp.renci.org/pub/irods/releases/4.1.9/centos6/irods-icommands-4.1.9-centos6-x86_64.rpm
  - ftp://ftp.renci.org/pub/irods/releases/4.1.9/centos6/irods-dev-4.1.9-centos6-x86_64.rpm

build_cmd: ./build.sh
