---

- name: set environment variables for legacy systems
  set_fact: ansible_python_interpreter=/usr/bin/python
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

###################
#  CHECK FOR GUI  #
###################
- name: Verify that X server exists
  stat:
    path: '{{ XGUI.xsession_path }}'
  register: xsession

- name: Verify that xterm session exists
  stat:
    path: '{{ XGUI.xterm_path }}'
  register: xterm

- name: Set flag for GUI systems
  set_fact:
    has_gui: '{{ xsession.stat.exists and xterm.stat.exists }}'

- name: Include tasks for install if has_gui
  include: install.yml
  when: has_gui
