---

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

# CHECK FOR GUI
- name: Verify that X server exists
  stat:
    path: '{{ xsession_path }}'
  register: xsession

- name: Verify that xterm session exists
  stat:
    path: '{{ xterm_path }}'
  register: xterm

- name: Set flag for GUI systems
  set_fact:
    has_gui: '{{ xsession.stat.exists and xterm.stat.exists }}'

- name: Include tasks for install if has_gui
  include: install.yml
  when: has_gui
