- name: make idrop folder
  file: path=/opt/irodsidrop state=directory

- name: copy idrop-latetest jar over
  copy: src=idrop.jar dest=/opt/irodsidrop/idrop-latest.jar

- name: copy over idroprun.sh
  copy: src=idroprun.sh dest=/opt/irodsidrop/ mode=0755

- name: copy over idrop.tgz
  copy: src=idrop.tgz dest=/opt/idrop.tgz

- name: open idrop tar
  unarchive: src=/opt/idrop.tgz dest=/opt/ copy=no

- name: make desktop folder in /etc/skel
  file: path=/etc/skel/Desktop state=directory

- name: copy over idrop.desktop to /etc/skel
  copy: src=idrop.desktop dest=/etc/skel/Desktop/idrop.desktop

- name: add atmousername to home directory just in case
  file: path=/home/{{ ATMOUSERNAME }}/Desktop state=directory

- name: find and replace old idrop.desktop files with new one
  shell: find /home -name "idrop.desktop" -exec cp /etc/skel/Desktop/idrop.desktop {} \;

- name: register each home directory
  shell: find /home/*/Desktop | cut -d/ -f3 | sort | uniq
  register: contents

- name: copy idrop.desktop to each Desktop folder in the /home/users/
  copy: src=idrop.desktop dest=/home/{{ item }}/Desktop/idrop.desktop
  with_items: '{{ contents.stdout_lines }}'

- name: chown idrop.desktop file in users home
  file: path=/home/{{ item }}/Desktop/idrop.desktop owner="{{ item }}" group=iplant-everyone mode=0744
  with_items: '{{ contents.stdout_lines }}'

- name: delete some files
  file: path=/opt/irodsidrop state=absent
