---

- name: Add users ssh keys to authorized_keys
  authorized_key: user=root key="{{ item }}" state=present
  with_items: '{{ USERSSHKEYS }}'
  become: yes
  when: USERSSHKEYS is defined

- name: Add users ssh keys to authorized_keys to home directory of user
  authorized_key: 'user={{ ATMOUSERNAME }} key={{ USERSSHKEYS|join("\n") }} state=present exclusive=no'
  when: USERSSHKEYS is defined and USERSSHKEYS != ""
