---
# defaults file for atmo-novnc

NOVNC:
  socket_port: 4200
  vnc_port: 5902
  vnc_session: 2
  # RealVNC Password Location
  passwd_file: /home/{{ ATMOUSERNAME }}/.vnc/config.d/Xvnc
  config_file: /home/{{ ATMOUSERNAME }}/.vnc/config.insecure

REQUIRED:
  files_to_add:
  files_to_remove:
    - { PATH: /tmp/.X1-lock, STATE: absent }
    - { PATH: /tmp/.X11-unix, STATE: absent }
    - { PATH: /tmp/novnc.tar, STATE: absent }
  dirs_to_make:
    - { PATH: /tmp/.X11-unix, STATE: directory, MODE: "a+rwxt", OWNER: "root" }
    - { PATH: "/home/{{ ATMOUSERNAME }}", STATE: directory, MODE: "0750", OWNER: "{{ ATMOUSERNAME }}" }
    - { PATH: "/home/{{ ATMOUSERNAME }}/.vnc", STATE: directory, MODE: "0750", OWNER: "{{ ATMOUSERNAME }}" }

VNC_COMMANDS:
  - "/usr/bin/pkill websockify"
  - "for i in $(/usr/bin/pgrep -f '/opt/kanaka-noVNC-8b0a0f6/utils/');do /bin/echo 'killing process:' $i; /bin/kill -HUP $i;done"
  - "/bin/su {{ ATMOUSERNAME }} -c '/usr/bin/vncserver -localhost :{{ NOVNC.vnc_session }} -SecurityTypes=VNCAuth,TLSVnc'"
  # To disable NoVNC web when entering prod, remove "--web /usr/share/novnc/" from the command below
  - "websockify -D --web /usr/share/novnc/ {{ NOVNC.socket_port }} localhost:{{ NOVNC.vnc_port }} &"

  # Systems to check
  # display 32,29,25 auth 27
